/**
 * Per-bank colour, used to make a card look like a card.
 *
 * These are approximations of each issuer's brand palette, used only as a
 * background wash so cards are recognisable at a glance. Deliberately NOT
 * their logos or wordmarks: shipping those would imply an affiliation
 * CardCircle does not have. A colour is decoration; a logo is a claim.
 *
 * Colours live here rather than in the database because they are
 * presentation, and putting them in `banks` would mean a migration every
 * time a brand refreshes.
 */

export type BankTheme = {
  /** Gradient start and end for the card face. */
  from: string
  to: string
  /** Text colour that meets contrast on that gradient. */
  ink: string
  /** Muted text on the same background. */
  inkMuted: string
  /**
   * Short label for the corner mark.
   *
   * Stated explicitly rather than derived: deriving it truncated codes to
   * four characters, which turned ICICI into "ICIC" and Kotak Mahindra into
   * "KM". A bank's short name is the name people use, not an abbreviation
   * rule — so it is data, not logic.
   */
  label: string
}

const LIGHT_INK = { ink: '#ffffff', inkMuted: 'rgba(255,255,255,0.72)' }
const DARK_INK = { ink: '#10131a', inkMuted: 'rgba(16,19,26,0.66)' }

const THEMES: Record<string, BankTheme> = {
  // Hues are assigned by construction, not copied from each brand.
  //
  // Most Indian banks brand themselves blue, and a faithful palette made
  // HDFC, SBI, Canara, Union, RBL, Yes, Central and Citi indistinguishable
  // on screen — which defeats the point of colouring a card by its issuer.
  //
  // Each bank claims the slot nearest its real brand hue on an evenly
  // divided wheel, so the recognisable ones stay close to their colour and
  // no two banks land on top of each other. Generated by the script in this
  // file's history; `bank-theme.test.ts` asserts the separation holds.
  HDFC: { from: '#0a3c66', to: '#217cca', ...LIGHT_INK, label: 'HDFC' },
  ICICI: { from: '#66350a', to: '#ca6f21', ...LIGHT_INK, label: 'ICICI' },
  AXIS: { from: '#660a35', to: '#ca216f', ...LIGHT_INK, label: 'AXIS' },
  KOTAK: { from: '#660a0a', to: '#ca2121', ...LIGHT_INK, label: 'KOTAK' },
  SBI: { from: '#2d0a66', to: '#6221ca', ...LIGHT_INK, label: 'SBI' },
  AMEX: { from: '#0a5166', to: '#21a3ca', ...LIGHT_INK, label: 'AMEX' },
  IDFC: { from: '#660a1f', to: '#ca2148', ...LIGHT_INK, label: 'IDFC' },
  CANARA: { from: '#0a6626', to: '#21ca55', ...LIGHT_INK, label: 'Canara' },
  UNION: { from: '#0a6666', to: '#21caca', ...LIGHT_INK, label: 'Union' },
  RBL: { from: '#0a2666', to: '#2155ca', ...LIGHT_INK, label: 'RBL' },
  INDUSIND: { from: '#660a4a', to: '#ca2196', ...LIGHT_INK, label: 'IndusInd' },
  YES: { from: '#0a6651', to: '#21caa3', ...LIGHT_INK, label: 'YES' },
  BOB: { from: '#664a0a', to: '#dda62c', ...DARK_INK, label: 'BoB' },
  PNB: { from: '#661f0a', to: '#ca4821', ...LIGHT_INK, label: 'PNB' },
  IDBI: { from: '#0a663c', to: '#21ca7c', ...LIGHT_INK, label: 'IDBI' },
  FEDERAL: { from: '#665f0a', to: '#ddcf2c', ...DARK_INK, label: 'Federal' },
  BOI: { from: '#58660a', to: '#b0ca21', ...LIGHT_INK, label: 'BoI' },
  INDIANBANK: { from: '#430a66', to: '#8921ca', ...LIGHT_INK, label: 'Indian' },
  CENTRAL: { from: '#0a1166', to: '#212eca', ...LIGHT_INK, label: 'Central' },
  AUSFB: { from: '#660a5f', to: '#ca21bd', ...LIGHT_INK, label: 'AU' },
  BANDHAN: { from: '#580a66', to: '#b021ca', ...LIGHT_INK, label: 'Bandhan' },
  SCB: { from: '#0a6611', to: '#21ca2e', ...LIGHT_INK, label: 'SC' },
  HSBC: { from: '#43660a', to: '#89ca21', ...LIGHT_INK, label: 'HSBC' },
  CITI: { from: '#180a66', to: '#3b21ca', ...LIGHT_INK, label: 'Citi' },
  DBS: { from: '#2d660a', to: '#62ca21', ...LIGHT_INK, label: 'DBS' },
  CSB: { from: '#18660a', to: '#3bca21', ...LIGHT_INK, label: 'CSB' },
}


/** Neutral slate for any bank without a defined palette. */
const FALLBACK: BankTheme = {
  from: '#2d3748',
  to: '#4a5568',
  ...LIGHT_INK,
  label: '',
}

export function bankTheme(code: string): BankTheme {
  return THEMES[code.toUpperCase()] ?? FALLBACK
}

/** `linear-gradient(...)` for a card face, or any bank-coloured surface. */
export function bankGradient(code: string): string {
  const theme = bankTheme(code)
  return `linear-gradient(135deg, ${theme.from} 0%, ${theme.to} 100%)`
}

// --- per-card variation ----------------------------------------------------

/** Stable 32-bit hash. Same seed always yields the same card. */
function hashSeed(seed: string): number {
  let hash = 2166136261
  for (let i = 0; i < seed.length; i += 1) {
    hash ^= seed.charCodeAt(i)
    hash = Math.imul(hash, 16777619)
  }
  return Math.abs(hash)
}

function hexToHsl(hex: string): [number, number, number] {
  const value = hex.replace('#', '')
  const r = parseInt(value.slice(0, 2), 16) / 255
  const g = parseInt(value.slice(2, 4), 16) / 255
  const b = parseInt(value.slice(4, 6), 16) / 255

  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  const lightness = (max + min) / 2
  const delta = max - min

  if (delta === 0) return [0, 0, lightness * 100]

  const saturation =
    lightness > 0.5 ? delta / (2 - max - min) : delta / (max + min)

  let hue: number
  if (max === r) hue = ((g - b) / delta + (g < b ? 6 : 0)) / 6
  else if (max === g) hue = ((b - r) / delta + 2) / 6
  else hue = ((r - g) / delta + 4) / 6

  return [hue * 360, saturation * 100, lightness * 100]
}

const clamp = (value: number, min: number, max: number): number =>
  Math.min(max, Math.max(min, value))

/**
 * A card face that is recognisably its bank, but not identical to its
 * neighbours.
 *
 * A bank page showed every card in exactly the same blue, because the
 * gradient came from the bank alone — a wall of identical rectangles that is
 * genuinely hard to read. This nudges hue, saturation, lightness and the
 * gradient angle by a small amount derived from the card's own seed, so two
 * HDFC cards differ at a glance while both still read as HDFC.
 *
 * The shifts are deliberately small. Push them further and an Axis card
 * starts looking like an SBI one, which would be worse than the monotony.
 *
 * Deterministic: the same card is the same colour on every render and every
 * device, so people can learn to recognise their own.
 */
export function bankGradientFor(code: string, seed: string): string {
  const theme = bankTheme(code)
  const hash = hashSeed(seed)

  const hueShift = ((hash % 37) - 18) * 1.0
  const satShift = (((hash >> 5) % 31) - 15) * 1.0
  // The widest of the three: lightness separates neighbouring cards far more
  // readably than hue does when a bank's whole palette is one colour family.
  const lightShift = (((hash >> 10) % 27) - 13) * 1.0
  const angle = 100 + ((hash >> 15) % 120)

  const shift = (hex: string, extraLight: number): string => {
    const [h, sat, l] = hexToHsl(hex)
    return `hsl(${(h + hueShift + 360) % 360} ${clamp(sat + satShift, 14, 94)}% ${clamp(l + lightShift + extraLight, 16, 58)}%)`
  }

  return `linear-gradient(${angle}deg, ${shift(theme.from, 0)} 0%, ${shift(theme.to, 2)} 100%)`
}

/**
 * Short label shown on the card face and bank tiles.
 *
 * Falls back to the bank's code for anything not in the table, truncated
 * only as a last resort.
 */
export function bankInitials(code: string, name: string): string {
  const known = THEMES[code.toUpperCase()]
  if (known?.label) return known.label
  if (code.length <= 8) return code.toUpperCase()
  return name.split(/\s+/)[0]?.slice(0, 8).toUpperCase() ?? code.slice(0, 8)
}


/**
 * A repeating pattern for the card face.
 *
 * Colour alone was not enough. Within one bank every card sits in the same
 * hue family, so a page of HDFC cards read as a wall of identical blue even
 * after shifting hue and lightness. Texture separates them at a glance in a
 * way a few degrees of hue cannot, without pulling any card away from its
 * bank's colour.
 *
 * Returned as a CSS background-image for a low-opacity overlay, so it rides
 * on top of the gradient rather than replacing it.
 */
export function cardPattern(seed: string): string | undefined {
  const variant = hashSeed(`pattern:${seed}`) % 6
  const ink = 'rgba(255,255,255,0.09)'
  const inkSoft = 'rgba(255,255,255,0.06)'

  switch (variant) {
    case 0: // diagonal stripes
      return `repeating-linear-gradient(45deg, ${ink} 0 6px, transparent 6px 16px)`
    case 1: // dots
      return `radial-gradient(circle at 2px 2px, ${ink} 1.5px, transparent 0)`
    case 2: // grid
      return `repeating-linear-gradient(0deg, ${inkSoft} 0 1px, transparent 1px 18px), repeating-linear-gradient(90deg, ${inkSoft} 0 1px, transparent 1px 18px)`
    case 3: // concentric glow
      return `radial-gradient(circle at 85% 15%, ${ink} 0 12%, transparent 40%), radial-gradient(circle at 15% 90%, ${inkSoft} 0 18%, transparent 45%)`
    case 4: // chevrons
      return `repeating-linear-gradient(135deg, ${inkSoft} 0 4px, transparent 4px 14px)`
    default: // plain, so not every card is busy
      return undefined
  }
}

/** Background-size to pair with cardPattern(). */
export function cardPatternSize(seed: string): string | undefined {
  const variant = hashSeed(`pattern:${seed}`) % 6
  if (variant === 1) return '14px 14px'
  if (variant === 2) return '18px 18px'
  return undefined
}
