-- The issuer's own page for each card product.
--
-- Answers the question a card's name asks: "what does this card actually get
-- me?" CardCircle does not know the offers and should not claim to, so the
-- name links to the bank's page for that card instead.
--
-- The column is nullable on purpose. 149 of the catalogue's products have a
-- confirmed page; the rest fall back to the bank's card-listing page, which
-- lives in code (src/lib/bank-links.ts) because a bank redesigning its site
-- should not need a database migration.
--
-- Every URL here came from the issuer's own sitemap or card-listing page and
-- was then fetched. See src/db/card-product-urls.ts for what that does and
-- does not guarantee.

ALTER TABLE "card_products" ADD COLUMN "product_url" text;--> statement-breakpoint

-- Enforced in the database, not only in Zod: a future code path with a bug
-- must not be able to store a javascript: or http: link that the UI would
-- then render as a bank's own page. The host allowlist cannot be expressed
-- here (it depends on the bank), so it stays in the application; this is the
-- floor beneath it.
ALTER TABLE "card_products" ADD CONSTRAINT "card_products_url_https"
  CHECK ("product_url" IS NULL OR "product_url" LIKE 'https://%');--> statement-breakpoint

UPDATE "card_products" p
SET "product_url" = v.url
FROM (VALUES
  ('HDFC', 'credit', '6e-rewards-indigo-hdfc', 'https://www.hdfc.bank.in/credit-cards/6e-rewards-indigo-credit-card'),
  ('HDFC', 'credit', 'hdfc-business-regalia', 'https://www.hdfc.bank.in/business-credit-cards/business-regalia-credit-card'),
  ('HDFC', 'credit', 'hdfc-diners-club-black', 'https://www.hdfc.bank.in/credit-cards/diners-club-black-credit-card'),
  ('HDFC', 'credit', 'hdfc-freedom', 'https://www.hdfc.bank.in/credit-cards/freedom-credit-card'),
  ('HDFC', 'credit', 'hdfc-infinia', 'https://www.hdfc.bank.in/credit-cards/infinia-credit-card'),
  ('HDFC', 'credit', 'hdfc-millennia', 'https://www.hdfc.bank.in/credit-cards/millennia-credit-card'),
  ('HDFC', 'credit', 'hdfc-moneyback-plus', 'https://www.hdfc.bank.in/credit-cards/moneyback-plus-credit-card'),
  ('HDFC', 'credit', 'hdfc-regalia', 'https://www.hdfc.bank.in/credit-cards/regalia-credit-card'),
  ('HDFC', 'credit', 'hdfc-regalia-gold', 'https://www.hdfc.bank.in/credit-cards/regalia-gold-credit-card'),
  ('HDFC', 'credit', 'indianoil-hdfc', 'https://www.hdfc.bank.in/credit-cards/indianoil-hdfc-bank-credit-card'),
  ('HDFC', 'credit', 'marriott-bonvoy-hdfc', 'https://www.hdfc.bank.in/credit-cards/marriott-bonvoy-credit-card'),
  ('HDFC', 'credit', 'shoppers-stop-hdfc', 'https://www.hdfc.bank.in/credit-cards/shoppers-stop-credit-card'),
  ('HDFC', 'credit', 'swiggy-hdfc', 'https://www.hdfc.bank.in/credit-cards/swiggy-hdfc-bank-credit-card'),
  ('HDFC', 'credit', 'tata-neu-infinity-hdfc', 'https://www.hdfc.bank.in/credit-cards/tata-neu-infinity-hdfc-bank-credit-card'),
  ('HDFC', 'credit', 'tata-neu-plus-hdfc', 'https://www.hdfc.bank.in/credit-cards/tata-neu-plus-hdfc-bank-credit-card'),
  ('HDFC', 'debit', 'hdfc-easyshop-platinum-debit', 'https://www.hdfc.bank.in/debit-cards/easyshop-platinum-debit-card'),
  ('HDFC', 'debit', 'hdfc-millennia-debit', 'https://www.hdfc.bank.in/debit-cards/millennia-debit-card'),
  ('HDFC', 'debit', 'hdfc-rewards-debit', 'https://www.hdfc.bank.in/debit-cards/rewards-debit-card'),
  ('HDFC', 'debit', 'hdfc-times-points-debit', 'https://www.hdfc.bank.in/debit-cards/times-points-debit-card'),
  ('AXIS', 'credit', 'airtel-axis-bank', 'https://www.axis.bank.in/cards/credit-card/airtel-axis-bank-credit-card'),
  ('AXIS', 'credit', 'axis-ace', 'https://www.axis.bank.in/cards/credit-card/axis-bank-ace-credit-card'),
  ('AXIS', 'credit', 'axis-atlas', 'https://www.axis.bank.in/cards/credit-card/axis-bank-atlas-credit-card'),
  ('AXIS', 'credit', 'axis-horizon', 'https://www.axis.bank.in/cards/credit-card/axis-horizon-credit-card'),
  ('AXIS', 'credit', 'axis-magnus', 'https://www.axis.bank.in/cards/credit-card/axis-bank-magnus-credit-card'),
  ('AXIS', 'credit', 'axis-my-zone', 'https://www.axis.bank.in/cards/credit-card/axis-bank-my-zone-credit-card'),
  ('AXIS', 'credit', 'axis-neo', 'https://www.axis.bank.in/cards/credit-card/axis-bank-neo-credit-card'),
  ('AXIS', 'credit', 'axis-reserve', 'https://www.axis.bank.in/cards/credit-card/reserve-credit-card'),
  ('AXIS', 'credit', 'axis-rewards', 'https://www.axis.bank.in/cards/credit-card/rewards-credit-card'),
  ('AXIS', 'credit', 'axis-select', 'https://www.axis.bank.in/cards/credit-card/axis-bank-select-credit-card'),
  ('AXIS', 'credit', 'axis-vistara', 'https://www.axis.bank.in/cards/credit-card/axis-bank-vistara-credit-card'),
  ('AXIS', 'credit', 'axis-vistara-infinite', 'https://www.axis.bank.in/cards/credit-card/axis-bank-vistara-infinite-credit-card'),
  ('AXIS', 'credit', 'flipkart-axis-bank', 'https://www.axis.bank.in/cards/credit-card/flipkart-axisbank-credit-card'),
  ('AXIS', 'credit', 'indianoil-axis-bank', 'https://www.axis.bank.in/cards/credit-card/indianoil-axis-bank-credit-card'),
  ('AXIS', 'credit', 'samsung-axis-bank-infinite', 'https://www.axis.bank.in/cards/credit-card/samsung-axis-bank-infinite-credit-card'),
  ('AXIS', 'credit', 'samsung-axis-bank-signature', 'https://www.axis.bank.in/cards/credit-card/samsung-axis-bank-signature-credit-card'),
  ('AXIS', 'debit', 'axis-burgundy-debit', 'https://www.axis.bank.in/cards/debit-card/burgundy-debit-card'),
  ('AXIS', 'debit', 'axis-liberty-debit', 'https://www.axis.bank.in/cards/debit-card/liberty-debit-card'),
  ('AXIS', 'debit', 'axis-prestige-debit', 'https://www.axis.bank.in/cards/debit-card/prestige-debit-card'),
  ('AXIS', 'debit', 'axis-priority-debit', 'https://www.axis.bank.in/cards/debit-card/priority-debit-card'),
  ('SBI', 'credit', 'air-india-sbi-signature', 'https://www.sbicard.com/en/personal/credit-cards/travel/air-india-sbi-signature-card.page'),
  ('SBI', 'credit', 'bpcl-sbi-card', 'https://www.sbicard.com/en/personal/credit-cards/travel/bpcl-sbi-card.page'),
  ('SBI', 'credit', 'bpcl-sbi-octane', 'https://www.sbicard.com/en/personal/credit-cards/travel/bpcl-sbi-card-octane.page'),
  ('SBI', 'credit', 'club-vistara-sbi', 'https://www.sbicard.com/en/personal/credit-cards/travel/club-vistara-sbi-card.page'),
  ('SBI', 'credit', 'irctc-sbi-platinum', 'https://www.sbicard.com/en/personal/credit-cards/travel/irctc-sbi-platinum-card.page'),
  ('SBI', 'credit', 'sbi-card-elite', 'https://www.sbicard.com/en/personal/credit-cards/lifestyle/sbi-card-elite.page'),
  ('SBI', 'credit', 'sbi-card-prime', 'https://www.sbicard.com/en/personal/credit-cards/rewards/sbi-card-prime.page'),
  ('SBI', 'credit', 'sbi-card-pulse', 'https://www.sbicard.com/en/personal/credit-cards/lifestyle/sbi-card-pulse.page'),
  ('SBI', 'credit', 'sbi-card-unnati', 'https://www.sbicard.com/en/personal/credit-cards/shopping/sbi-card-unnati.page'),
  ('SBI', 'credit', 'sbi-cashback-card', 'https://www.sbicard.com/en/personal/credit-cards/rewards/cashback-sbi-card.page'),
  ('SBI', 'credit', 'sbi-simplyclick', 'https://www.sbicard.com/en/personal/credit-cards/shopping/simplyclick-sbi-card.page'),
  ('SBI', 'credit', 'sbi-simplysave', 'https://www.sbicard.com/en/personal/credit-cards/shopping/simplysave-sbi-card.page'),
  ('SBI', 'credit', 'tata-neu-infinity-sbi', 'https://www.sbicard.com/en/personal/credit-cards/lifestyle/tata-neu-infinity-sbi-card.page'),
  ('SBI', 'debit', 'sbi-global-international-debit', 'https://sbi.bank.in/web/personal-banking/cards/debit-card/sbi-global-international-debit-car'),
  ('SBI', 'debit', 'sbi-gold-international-debit', 'https://sbi.bank.in/web/personal-banking/cards/debit-card/sbi-gold-international-debit-card'),
  ('SBI', 'debit', 'sbi-hpcl-co-branded-debit-card', 'https://sbi.bank.in/web/personal-banking/hpcl-co-branded-debit-card'),
  ('SBI', 'debit', 'sbi-iocl-co-branded-contactless-rupay-debit-card', 'https://sbi.bank.in/web/personal-banking/cards/debit-card/sbi-iocl-co-branded-contactless-rupay-debit-card'),
  ('SBI', 'debit', 'sbi-mastercard-world-debit-card', 'https://sbi.bank.in/web/personal-banking/sbi-mastercard-world-debit-card'),
  ('SBI', 'debit', 'sbi-my-card-international-debit-card', 'https://sbi.bank.in/web/personal-banking/cards/debit-card/sbi-my-card-international-debit-card'),
  ('SBI', 'debit', 'sbi-nari-shakti-platinum-debit-card', 'https://sbi.bank.in/web/personal-banking/sbi-nari-shakti-platinum-debit-card'),
  ('SBI', 'debit', 'sbi-platinum-international-debit', 'https://sbi.bank.in/web/personal-banking/cards/debit-card/sbi-platinum-international-debit-card'),
  ('SBI', 'debit', 'sbi-pragati-platinum-debit-card', 'https://sbi.bank.in/web/personal-banking/sbi-pragati-platinum-debit-card'),
  ('SBI', 'debit', 'sbi-virtual-debit-card', 'https://sbi.bank.in/web/personal-banking/cards/debit-card/sbi-virtual-debit-card'),
  ('SBI', 'debit', 'sbi-visa-infinite-debit-card', 'https://sbi.bank.in/web/personal-banking/cards/debit-card/visa-infinite-debit-card'),
  ('ICICI', 'credit', 'amazon-pay-icici', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/amazon-pay-credit-card'),
  ('ICICI', 'credit', 'hpcl-super-saver-icici', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/hpcl-super-saver'),
  ('ICICI', 'credit', 'icici-coral', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/coral-credit-card'),
  ('ICICI', 'credit', 'icici-emeralde', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/emeralde-credit-card'),
  ('ICICI', 'credit', 'icici-emeralde-private-metal', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/emeralde-private-metal-credit-card'),
  ('ICICI', 'credit', 'icici-expressions', 'https://www.icici.bank.in/personal-banking/cards/credit-card/expressions-card'),
  ('ICICI', 'credit', 'icici-platinum-chip', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/platinum-chip-credit-card'),
  ('ICICI', 'credit', 'icici-rubyx', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/rubyx-credit-card'),
  ('ICICI', 'credit', 'icici-sapphiro', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/sapphiro-card'),
  ('ICICI', 'credit', 'makemytrip-icici', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/credit-card/makemytrip/makemytrip-icici-bank-credit-card'),
  ('ICICI', 'debit', 'icici-coral-debit', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/debit-card/coral-debit-card'),
  ('ICICI', 'debit', 'icici-expressions-debit', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/debit-card/expressions-debit-card'),
  ('ICICI', 'debit', 'icici-platinum-chip-debit', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/debit-card/platinum-chip-card'),
  ('ICICI', 'debit', 'icici-rubyx-debit', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/debit-card/rubyx-debit-card'),
  ('ICICI', 'debit', 'icici-sapphiro-debit', 'https://www.icici.bank.in/content/icicibank-revamp/in/en/personal-banking/cards/debit-card/expressions-debit-card/sapphiro'),
  ('KOTAK', 'credit', 'kotak-811-dream-different', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/811-dream-different-credit-card.html'),
  ('KOTAK', 'credit', 'kotak-league-platinum', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/league-platinum-card.html'),
  ('KOTAK', 'credit', 'kotak-mojo-platinum', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/mojo-platinum-credit-card.html'),
  ('KOTAK', 'credit', 'kotak-royale-signature', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/royale-signature-credit-card.html'),
  ('KOTAK', 'credit', 'kotak-solitaire', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/kotak-solitaire-credit-card.html'),
  ('KOTAK', 'credit', 'kotak-white', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/white-credit-card.html'),
  ('KOTAK', 'credit', 'kotak-white-reserve', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/white-reserve-credit-card.html'),
  ('KOTAK', 'credit', 'kotak-zen-signature', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/zen-signature-credit-card.html'),
  ('KOTAK', 'credit', 'pvr-inox-kotak', 'https://www.kotak.bank.in/en/personal-banking/cards/credit-cards/pvr-inox-kotak-credit-card.html'),
  ('KOTAK', 'debit', 'kotak-platinum-debit', 'https://www.kotak.bank.in/en/personal-banking/cards/debit-cards/platinum-debit-card.html'),
  ('KOTAK', 'debit', 'kotak-silk-debit', 'https://www.kotak.bank.in/en/personal-banking/cards/debit-cards/silk-debit-card.html'),
  ('IDFC', 'credit', 'club-vistara-idfc-first', 'https://www.idfcfirst.bank.in/credit-card/vistara-credit-card'),
  ('IDFC', 'credit', 'idfc-first-classic', 'https://www.idfcfirst.bank.in/credit-card/classic'),
  ('IDFC', 'credit', 'idfc-first-millennia', 'https://www.idfcfirst.bank.in/credit-card/millennia'),
  ('IDFC', 'credit', 'idfc-first-power', 'https://www.idfcfirst.bank.in/credit-card/hpcl-power-fuel-credit-card'),
  ('IDFC', 'credit', 'idfc-first-power-plus', 'https://www.idfcfirst.bank.in/credit-card/hpcl-power-fuel-credit-card'),
  ('IDFC', 'credit', 'idfc-first-select', 'https://www.idfcfirst.bank.in/credit-card/select'),
  ('IDFC', 'credit', 'idfc-first-swyp', 'https://www.idfcfirst.bank.in/credit-card/swyp-emi-credit-card'),
  ('IDFC', 'credit', 'idfc-first-wealth', 'https://www.idfcfirst.bank.in/credit-card/wealth'),
  ('IDFC', 'credit', 'idfc-first-wow', 'https://www.idfcfirst.bank.in/credit-card/wow'),
  ('IDFC', 'debit', 'idfc-first-classic-debit', 'https://www.idfcfirst.bank.in/personal-banking/payments/cards/debit-card/classic-debit-card'),
  ('IDFC', 'debit', 'idfc-first-platinum-debit', 'https://www.idfcfirst.bank.in/personal-banking/payments/cards/debit-card/platinum-debit-card'),
  ('AMEX', 'credit', 'amex-membership-rewards', 'https://www.americanexpress.com/en-in/rewards/membership-rewards'),
  ('AMEX', 'credit', 'amex-platinum-reserve', 'https://www.americanexpress.com/in/credit-cards/platinum-reserve-credit-card'),
  ('AMEX', 'credit', 'amex-platinum-travel', 'https://www.americanexpress.com/in/credit-cards/platinum-travel-credit-card'),
  ('RBL', 'credit', 'rbl-icon', 'https://www.rbl.bank.in/personal-banking/cards/credit-cards/icon-credit-card'),
  ('RBL', 'credit', 'rbl-insignia-preferred-banking', 'https://www.rbl.bank.in/personal-banking/cards/credit-cards/insignia-preferred-banking-credit-card'),
  ('RBL', 'credit', 'rbl-platinum-maxima', 'https://www.rbl.bank.in/personal-banking/cards/credit-cards/platinum-maxima-credit-card'),
  ('RBL', 'credit', 'rbl-platinum-maxima-plus', 'https://www.rbl.bank.in/personal-banking/cards/credit-cards/platinum-maxima-plus-credit-card'),
  ('RBL', 'credit', 'rbl-popcorn', 'https://www.rbl.bank.in/personal-banking/cards/credit-cards/rbl-bank-popcorn-credit-card'),
  ('RBL', 'credit', 'rbl-shoprite', 'https://www.rbl.bank.in/personal-banking/cards/credit-cards/shoprite-credit-card'),
  ('RBL', 'credit', 'rbl-world-safari', 'https://www.rbl.bank.in/personal-banking/cards/credit-cards/world-safari-credit-card'),
  ('RBL', 'debit', 'rbl-classic-debit', 'https://www.rbl.bank.in/personal-banking/cards/debit-cards/classic-debit-card'),
  ('RBL', 'debit', 'rbl-platinum-debit', 'https://www.rbl.bank.in/personal-banking/cards/debit-cards/platinum-debit-card'),
  ('RBL', 'debit', 'rbl-signature-debit', 'https://www.rbl.bank.in/personal-banking/cards/debit-cards/signature-debit-card'),
  ('INDUSIND', 'credit', 'indusind-eazydiner', 'https://www.indusind.bank.in/in/en/personal/cards/credit-card/eazydiner-credit-card.html'),
  ('INDUSIND', 'credit', 'indusind-legend', 'https://www.indusind.bank.in/in/en/personal/cards/credit-card/legend-credit-card.html'),
  ('INDUSIND', 'credit', 'indusind-nexxt', 'https://www.indusind.bank.in/in/en/personal/cards/credit-card/nexxt-credit-card.html'),
  ('INDUSIND', 'credit', 'indusind-pinnacle', 'https://www.indusind.bank.in/in/en/personal/cards/credit-card/pinnacle-world-credit-card.html'),
  ('INDUSIND', 'credit', 'indusind-platinum-rupay', 'https://www.indusind.bank.in/in/en/personal/cards/credit-card/platinum-rupay-credit-card.html'),
  ('INDUSIND', 'credit', 'indusind-tiger', 'https://www.indusind.bank.in/in/en/personal/cards/credit-card/tiger-credit-card.html'),
  ('BOB', 'credit', 'bob-easy', 'https://www.bobcard.co.in/credit-card-types/easy'),
  ('BOB', 'credit', 'bob-eterna', 'https://www.bobcard.co.in/credit-card-types/eterna'),
  ('BOB', 'credit', 'bob-premier', 'https://www.bobcard.co.in/credit-card-types/premier'),
  ('BOB', 'credit', 'bob-select', 'https://www.bobcard.co.in/credit-card-types/select'),
  ('BOB', 'credit', 'bob-snapdeal', 'https://www.bobcard.co.in/credit-card-types/snapdeal-bobcard'),
  ('BOB', 'credit', 'irctc-bob', 'https://www.bobcard.co.in/credit-card-types/irctc-credit-card'),
  ('BOB', 'debit', 'bob-rupay-select-debit', 'https://bankofbaroda.bank.in/digital-products/cards/debit-cards/rupay-select-debit-card'),
  ('PNB', 'debit', 'pnb-platinum-debit', 'https://pnb.bank.in/Platinum-Debit-Card.html'),
  ('CANARA', 'credit', 'canara-mastercard-platinum', 'https://www.canarabank.bank.in/mastercard-platinum-credit-card'),
  ('CANARA', 'credit', 'canara-rupay-platinum', 'https://www.canarabank.bank.in/rupay-platinum-credit-card'),
  ('CANARA', 'credit', 'canara-rupay-select', 'https://canarabank.bank.in/pages/Rupay-Select-Credit-Card'),
  ('CANARA', 'credit', 'canara-visa-platinum', 'https://www.canarabank.bank.in/visa-platinum-credit-card'),
  ('UNION', 'credit', 'union-bank-rupay-select', 'https://www.unionbankofindia.bank.in/en/details/rupay-select-credit-card'),
  ('FEDERAL', 'credit', 'federal-bank-celesta', 'https://www.federal.bank.in/celesta-credit-card'),
  ('FEDERAL', 'credit', 'federal-bank-imperio', 'https://www.federal.bank.in/imperio-credit-card'),
  ('FEDERAL', 'credit', 'federal-bank-rupay-signet', 'https://www.federal.bank.in/rupay-signet-credit-card'),
  ('FEDERAL', 'credit', 'federal-bank-signet', 'https://www.federal.bank.in/signet-credit-card'),
  ('FEDERAL', 'debit', 'fedfirst-debit', 'https://www.federal.bank.in/fedfirst-contactless-debit-card'),
  ('SCB', 'credit', 'standard-chartered-digismart', 'https://www.sc.bank.in/credit-cards/digismart-card'),
  ('SCB', 'credit', 'standard-chartered-easemytrip', 'https://www.sc.bank.in/credit-cards/easemytrip-credit-card'),
  ('SCB', 'credit', 'standard-chartered-manhattan-platinum', 'https://www.sc.bank.in/credit-cards/manhattan-platinum'),
  ('SCB', 'credit', 'standard-chartered-platinum-rewards', 'https://www.sc.bank.in/credit-cards/platinum-rewards'),
  ('SCB', 'credit', 'standard-chartered-rewards', 'https://www.sc.bank.in/credit-cards/rewards-credit-card'),
  ('SCB', 'credit', 'standard-chartered-smart', 'https://www.sc.bank.in/credit-cards/smart-credit-card'),
  ('SCB', 'credit', 'standard-chartered-ultimate', 'https://www.sc.bank.in/credit-cards/ultimate-card'),
  ('SCB', 'debit', 'standard-chartered-platinum-debit', 'https://www.sc.bank.in/debit-cards/debit-card-platinum'),
  ('HSBC', 'credit', 'hsbc-travelone', 'https://www.hsbc.bank.in/credit-cards/products/travelone'),
  ('HSBC', 'credit', 'hsbc-visa-platinum', 'https://www.hsbc.bank.in/credit-cards/products/visa-platinum'),
  ('CSB', 'credit', 'edge-csb-bank-rupay-credit-card', 'https://www.csb.bank.in/csb-bank-edge-credit-card'),
  ('CSB', 'credit', 'edge-plus-csb-bank-rupay-credit-card', 'https://jupiter.money/edge-plus-upi-rupay-credit-card')
) AS v(code, card_type, slug, url)
JOIN "banks" b ON b."code" = v.code
WHERE p."bank_id" = b."id"
  AND p."card_type" = v.card_type::"card_type"
  AND p."slug" = v.slug;
